export * from "../modals/property/property.component";
export * from "../modals/auth/auth.modal";
export * from "../modals/add-ingridient-image/add-ingridient-image.modal";
export * from "../modals/remove/remove.modal";
export * from "../modals/like/like.modal";
export * from "../modals/gallery-modal/gallery-modal.modal";
export * from "../modals/specialties/specialties.modal";
export * from "../modals/profile-cover/profile-cover.modal";
export * from './tags/tags.modal'